### ISSUE TITLE
How to integrate inside ProcessStep and/or Pipeline?

### ISSUE THREAD

**Issue by jonathanglima** [aws-samples/smallmatter-package#10]
Hey, I'm trying to integrate with a pipeline that I'm building that's based on the Abalone example (https://docs.aws.amazon.com/sagemaker/latest/dg/define-pipeline.html)

I think that the .run method executes things outside the pipeline. Is there a way to orchestrate this inside the Sagemaker Pipeline?

**Comment by verdimrc** [comment]
Hi @jonathanglima, thank you for taking an interest. At the moment, SageMaker workflow cannot run this sample framework processor because this processor does not override the `get_run_args()`.

**Comment by verdimrc** [comment]
Hi, I'm going to close this issue, since the `get_run_args()` is implemented (and tracked) by the SageMaker PR [#2251](https://github.com/aws/sagemaker-python-sdk/pull/2251).
