### ISSUE TITLE
Bug: Error installing package

### ISSUE THREAD

**Issue by josiahdavis** [aws-samples/smallmatter-package#7]
I get an error when I try installing the smallmatter package using pip. It appears there is no version tag. See below for full output.

I tried both of the installation options listed on the README.
```
pip install \
    'git+https://github.com/aws-samples/smallmatter-package@v0.1.0#egg=smallmatter[all]'

pip install \                                                                                                        
    'git+https://github.com/aws-samples/smallmatter-package@v0.1.0#egg=smallmatter' 
```

The result is an error message:

**ERROR: Could not find a version that satisfies the requirement smallmatter (unavailable)**

**ERROR: No matching distribution found for smallmatter (unavailable)**

![Screenshot 2021-03-01 at 11 18 53 AM](https://user-images.githubusercontent.com/6405428/109448292-91799900-7a80-11eb-99ae-1e5c698ea21f.png)

**Comment by verdimrc** [comment]
Fixed. Thank you for the bug report.
